"""Add missing indexes for performance

Revision ID: 8ff9b0ac27cc
Revises: 23ad21251631
Create Date: 2026-04-29 18:08:13.012062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8ff9b0ac27cc'
down_revision: Union[str, Sequence[str], None] = '23ad21251631'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dashboard_summaries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=True),
    sa.Column('summary_date', sa.Date(), nullable=True),
    sa.Column('total_received', sa.Integer(), nullable=True),
    sa.Column('total_completed', sa.Integer(), nullable=True),
    sa.Column('total_pending', sa.Integer(), nullable=True),
    sa.Column('total_at_risk', sa.Integer(), nullable=True),
    sa.Column('average_velocity', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dashboard_summaries_customer_id'), 'dashboard_summaries', ['customer_id'], unique=False)
    op.create_index(op.f('ix_dashboard_summaries_summary_date'), 'dashboard_summaries', ['summary_date'], unique=False)
    op.drop_table('User')
    op.drop_table('Course')
    op.drop_index(op.f('Enrollment_userId_courseId_key'), table_name='Enrollment')
    op.drop_table('Enrollment')
    op.create_index('index_audit_resource_time', 'audit_logs', ['resource_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_candidates_client_emp_code'), 'candidates', ['client_emp_code'], unique=False)
    op.create_index(op.f('ix_candidates_pan_no'), 'candidates', ['pan_no'], unique=False)
    op.create_index(op.f('ix_candidates_passport_no'), 'candidates', ['passport_no'], unique=False)
    op.create_index(op.f('ix_candidates_phone'), 'candidates', ['phone'], unique=False)
    op.create_index('index_assigned_status', 'cases', ['assigned_to', 'status'], unique=False)
    op.create_index('index_customer_status', 'cases', ['customer_id', 'status'], unique=False)
    op.create_foreign_key(None, 'cases', 'batches', ['batch_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'cases', 'users', ['qa_id'], ['id'])
    op.create_foreign_key(None, 'cases', 'users', ['qc_id'], ['id'])
    op.create_foreign_key(None, 'cases', 'users', ['assigned_to'], ['id'])
    op.drop_column('cases', 'assigned_id')
    op.drop_index(op.f('ix_marked_at'), table_name='insufficiency_logs')
    op.create_index(op.f('ix_insufficiency_logs_case_id'), 'insufficiency_logs', ['case_id'], unique=False)
    op.create_index(op.f('ix_insufficiency_logs_marked_at'), 'insufficiency_logs', ['marked_at'], unique=False)
    op.create_index(op.f('ix_insufficiency_logs_user_id'), 'insufficiency_logs', ['user_id'], unique=False)
    op.create_index('index_user_unread', 'notifications', ['user_id', 'is_read'], unique=False)
    op.alter_column('users', 'role',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('SUPER_ADMIN', 'ADMIN', 'MANAGER', 'VERIFIER', 'QC', 'QA', 'CUSTOMER', 'CANDIDATE', 'USER', name='userrole'),
               existing_nullable=True)
    op.create_index('index_user_customer_status', 'users', ['customer_id', 'status'], unique=False)
    op.create_index(op.f('ix_verification_checks_case_id'), 'verification_checks', ['case_id'], unique=False)
    op.create_index(op.f('ix_verification_checks_check_type'), 'verification_checks', ['check_type'], unique=False)
    op.create_index(op.f('ix_verification_checks_status'), 'verification_checks', ['status'], unique=False)
    op.create_index(op.f('ix_verification_checks_verified_date'), 'verification_checks', ['verified_date'], unique=False)
    op.drop_constraint(op.f('verification_checks_ibfk_1'), 'verification_checks', type_='foreignkey')
    op.create_foreign_key(None, 'verification_checks', 'cases', ['case_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'verification_checks', type_='foreignkey')
    op.create_foreign_key(op.f('verification_checks_ibfk_1'), 'verification_checks', 'cases', ['case_id'], ['id'])
    op.drop_index(op.f('ix_verification_checks_verified_date'), table_name='verification_checks')
    op.drop_index(op.f('ix_verification_checks_status'), table_name='verification_checks')
    op.drop_index(op.f('ix_verification_checks_check_type'), table_name='verification_checks')
    op.drop_index(op.f('ix_verification_checks_case_id'), table_name='verification_checks')
    op.drop_index('index_user_customer_status', table_name='users')
    op.alter_column('users', 'role',
               existing_type=sa.Enum('SUPER_ADMIN', 'ADMIN', 'MANAGER', 'VERIFIER', 'QC', 'QA', 'CUSTOMER', 'CANDIDATE', 'USER', name='userrole'),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_index('index_user_unread', table_name='notifications')
    op.drop_index(op.f('ix_insufficiency_logs_user_id'), table_name='insufficiency_logs')
    op.drop_index(op.f('ix_insufficiency_logs_marked_at'), table_name='insufficiency_logs')
    op.drop_index(op.f('ix_insufficiency_logs_case_id'), table_name='insufficiency_logs')
    op.create_index(op.f('ix_marked_at'), 'insufficiency_logs', ['marked_at'], unique=False)
    op.add_column('cases', sa.Column('assigned_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'cases', type_='foreignkey')
    op.drop_constraint(None, 'cases', type_='foreignkey')
    op.drop_constraint(None, 'cases', type_='foreignkey')
    op.drop_constraint(None, 'cases', type_='foreignkey')
    op.drop_index('index_customer_status', table_name='cases')
    op.drop_index('index_assigned_status', table_name='cases')
    op.drop_index(op.f('ix_candidates_phone'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_passport_no'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_pan_no'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_client_emp_code'), table_name='candidates')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index('index_audit_resource_time', table_name='audit_logs')
    op.create_table('Enrollment',
    sa.Column('id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), nullable=False),
    sa.Column('userId', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), nullable=False),
    sa.Column('courseId', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), nullable=False),
    sa.Column('createdAt', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.ForeignKeyConstraint(['courseId'], ['Course.id'], name=op.f('Enrollment_courseId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], name=op.f('Enrollment_userId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('Enrollment_userId_courseId_key'), 'Enrollment', ['userId', 'courseId'], unique=True)
    op.create_table('Course',
    sa.Column('id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), nullable=False),
    sa.Column('title', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), nullable=False),
    sa.Column('description', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), nullable=False),
    sa.Column('price', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), nullable=False),
    sa.Column('modes', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), nullable=False),
    sa.Column('duration', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), nullable=False),
    sa.Column('outcome', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), nullable=False),
    sa.Column('image', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), server_default=sa.text("'/placeholder.png'"), nullable=False),
    sa.Column('category', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), server_default=sa.text("'General'"), nullable=False),
    sa.Column('createdAt', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.Column('updatedAt', mysql.DATETIME(fsp=3), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('User',
    sa.Column('id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), server_default=sa.text("'Student'"), nullable=False),
    sa.Column('email', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), nullable=False),
    sa.Column('password', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), nullable=False),
    sa.Column('role', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), server_default=sa.text("'STUDENT'"), nullable=False),
    sa.Column('createdAt', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.Column('updatedAt', mysql.DATETIME(fsp=3), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_dashboard_summaries_summary_date'), table_name='dashboard_summaries')
    op.drop_index(op.f('ix_dashboard_summaries_customer_id'), table_name='dashboard_summaries')
    op.drop_table('dashboard_summaries')
    # ### end Alembic commands ###
