"""Baseline plus performance indexes

Revision ID: dec6ee93263d
Revises: 
Create Date: 2026-04-12 12:59:16.968678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'dec6ee93263d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_candidates_name'), 'candidates', ['name'], unique=False)
    op.create_index(op.f('ix_batches_customer_id'), 'batches', ['customer_id'], unique=False)
    op.create_index(op.f('ix_cases_customer_id'), 'cases', ['customer_id'], unique=False)
    op.create_index(op.f('ix_cases_candidate_id'), 'cases', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_verification_checks_case_id'), 'verification_checks', ['case_id'], unique=False)
    op.create_index(op.f('ix_verification_checks_check_type'), 'verification_checks', ['check_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'verification_checks', type_='foreignkey')
    op.create_foreign_key(op.f('verification_checks_ibfk_1'), 'verification_checks', 'cases', ['case_id'], ['id'])
    op.drop_index(op.f('ix_verification_checks_verified_date'), table_name='verification_checks')
    op.drop_index(op.f('ix_verification_checks_status'), table_name='verification_checks')
    op.drop_index(op.f('ix_verification_checks_check_type'), table_name='verification_checks')
    op.drop_index(op.f('ix_verification_checks_case_id'), table_name='verification_checks')
    op.alter_column('users', 'role',
               existing_type=sa.Enum('SUPER_ADMIN', 'ADMIN', 'MANAGER', 'VERIFIER', 'QC', 'QA', 'CUSTOMER', 'CANDIDATE', 'USER', name='userrole'),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_constraint(None, 'cases', type_='foreignkey')
    op.drop_constraint(None, 'cases', type_='foreignkey')
    op.create_table('Course',
    sa.Column('id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), nullable=False),
    sa.Column('title', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), nullable=False),
    sa.Column('description', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), nullable=False),
    sa.Column('price', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), nullable=False),
    sa.Column('modes', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), nullable=False),
    sa.Column('duration', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), nullable=False),
    sa.Column('outcome', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), nullable=False),
    sa.Column('image', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), server_default=sa.text("'/placeholder.png'"), nullable=False),
    sa.Column('category', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), server_default=sa.text("'General'"), nullable=False),
    sa.Column('createdAt', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.Column('updatedAt', mysql.DATETIME(fsp=3), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('User',
    sa.Column('id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), server_default=sa.text("'Student'"), nullable=False),
    sa.Column('email', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), nullable=False),
    sa.Column('password', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), nullable=False),
    sa.Column('role', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), server_default=sa.text("'STUDENT'"), nullable=False),
    sa.Column('createdAt', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.Column('updatedAt', mysql.DATETIME(fsp=3), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Enrollment',
    sa.Column('id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), nullable=False),
    sa.Column('userId', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), nullable=False),
    sa.Column('courseId', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), nullable=False),
    sa.Column('createdAt', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.ForeignKeyConstraint(['courseId'], ['Course.id'], name=op.f('Enrollment_courseId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], name=op.f('Enrollment_userId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('Enrollment_userId_courseId_key'), 'Enrollment', ['userId', 'courseId'], unique=True)
    # ### end Alembic commands ###
