"""Add ai_summary column to cases

Revision ID: e3b2f39e55bb
Revises: dec6ee93263d
Create Date: 2026-04-17 10:24:27.630986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e3b2f39e55bb'
down_revision: Union[str, Sequence[str], None] = 'dec6ee93263d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add ai_summary to cases
    op.add_column('cases', sa.Column('ai_summary', sa.Text(), nullable=True))
    
    # Add resource_id to audit_logs if missing (it matches models.py)
    op.add_column('audit_logs', sa.Column('resource_id', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_audit_logs_resource_id'), 'audit_logs', ['resource_id'], unique=False)
    
    # Fix case columns type (String(36) to match other IDs)
    op.alter_column('cases', 'qa_id',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=True)
    op.alter_column('cases', 'qc_id',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=True)
    op.create_index(op.f('ix_cases_qa_id'), 'cases', ['qa_id'], unique=False)
    op.create_index(op.f('ix_cases_qc_id'), 'cases', ['qc_id'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'verification_checks', type_='foreignkey')
    op.create_foreign_key(op.f('verification_checks_ibfk_1'), 'verification_checks', 'cases', ['case_id'], ['id'])
    op.drop_index(op.f('ix_verification_checks_verified_date'), table_name='verification_checks')
    op.drop_index(op.f('ix_verification_checks_status'), table_name='verification_checks')
    op.drop_index(op.f('ix_verification_checks_check_type'), table_name='verification_checks')
    op.drop_index(op.f('ix_verification_checks_case_id'), table_name='verification_checks')
    op.alter_column('users', 'role',
               existing_type=sa.Enum('SUPER_ADMIN', 'ADMIN', 'MANAGER', 'VERIFIER', 'QC', 'QA', 'CUSTOMER', 'CANDIDATE', 'USER', name='userrole'),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
    op.add_column('cases', sa.Column('assigned_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'cases', type_='foreignkey')
    op.drop_constraint(None, 'cases', type_='foreignkey')
    op.drop_constraint(None, 'cases', type_='foreignkey')
    op.drop_constraint(None, 'cases', type_='foreignkey')
    op.drop_index(op.f('ix_cases_qc_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_qa_id'), table_name='cases')
    op.alter_column('cases', 'qc_id',
               existing_type=sa.String(length=36),
               type_=mysql.INTEGER(),
               existing_nullable=True)
    op.alter_column('cases', 'qa_id',
               existing_type=sa.String(length=36),
               type_=mysql.INTEGER(),
               existing_nullable=True)
    op.drop_column('cases', 'ai_summary')
    op.drop_index(op.f('ix_audit_logs_resource_id'), table_name='audit_logs')
    op.drop_column('audit_logs', 'resource_id')
    op.create_table('User',
    sa.Column('id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), server_default=sa.text("'Student'"), nullable=False),
    sa.Column('email', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), nullable=False),
    sa.Column('password', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), nullable=False),
    sa.Column('role', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), server_default=sa.text("'STUDENT'"), nullable=False),
    sa.Column('createdAt', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.Column('updatedAt', mysql.DATETIME(fsp=3), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Course',
    sa.Column('id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), nullable=False),
    sa.Column('title', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), nullable=False),
    sa.Column('description', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), nullable=False),
    sa.Column('price', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), nullable=False),
    sa.Column('modes', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), nullable=False),
    sa.Column('duration', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), nullable=False),
    sa.Column('outcome', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), nullable=False),
    sa.Column('image', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), server_default=sa.text("'/placeholder.png'"), nullable=False),
    sa.Column('category', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), server_default=sa.text("'General'"), nullable=False),
    sa.Column('createdAt', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.Column('updatedAt', mysql.DATETIME(fsp=3), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Enrollment',
    sa.Column('id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), nullable=False),
    sa.Column('userId', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), nullable=False),
    sa.Column('courseId', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=191), nullable=False),
    sa.Column('createdAt', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False),
    sa.ForeignKeyConstraint(['courseId'], ['Course.id'], name=op.f('Enrollment_courseId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], name=op.f('Enrollment_userId_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('Enrollment_userId_courseId_key'), 'Enrollment', ['userId', 'courseId'], unique=True)
    # ### end Alembic commands ###
