import enum

class UserRole(str, enum.Enum):
    SUPER_ADMIN = "SUPER_ADMIN"
    ADMIN = "SUPER_ADMIN"
    MANAGER = "MANAGER"
    VERIFIER = "VERIFIER"
    QC = "VERIFIER"
    QA = "VERIFIER"
    CUSTOMER = "CUSTOMER"
    CANDIDATE = "CANDIDATE"
    USER = "VERIFIER"

class Status(str, enum.Enum):
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"

class CaseStatus(str, enum.Enum):
    ASSIGNED = "ASSIGNED"
    IN_PROGRESS = "IN_PROGRESS"
    INSUFFICIENCY = "INSUFFICIENCY"
    FINALIZED = "FINALIZED"
    POSITIVE = "POSITIVE"
    NEGATIVE = "NEGATIVE"
    DISCREPANCY = "DISCREPANCY"
    UNABLE_TO_VERIFY = "UNABLE TO VERIFY"
    INSUFFICIENT = "INSUFFICIENT"
    HOLD = "HOLD"

    # Aliases and Legacy Fallbacks
    PENDING = "ASSIGNED"
    # INSUFFICIENT = "INSUFFICIENCY"
    COMPLETED = "FINALIZED"
    CLOSED = "FINALIZED"
    NEW = "ASSIGNED"
    LINK_SHARED = "ASSIGNED"
    IN_VERIFICATION = "IN_PROGRESS"
    QC_REVIEW = "FINALIZED"
    REOPENED = "IN_PROGRESS"
    CANCELLED = "FINALIZED"
    VERIFICATION = "IN_PROGRESS"
    QC = "FINALIZED"
    QA_PENDING = "FINALIZED"
    QC_PENDING = "FINALIZED"
    QC_VERIFIED = "FINALIZED"
    DOCUMENTS_SUBMITTED = "IN_PROGRESS"

class CheckStatus(str, enum.Enum):
    POSITIVE = "POSITIVE"
    NEGATIVE = "NEGATIVE"
    DISCREPANCY = "DISCREPANCY"
    INTERIM = "INTERIM"
    INSUFFICIENT = "INSUFFICIENT"
    NOT_APPLICABLE = "NOT_APPLICABLE"
    # Legacy fallbacks
    GREEN = "GREEN"
    RED = "RED"
    AMBER = "AMBER"
    PENDING = "PENDING"
    IN_PROGRESS = "IN_PROGRESS"
    VERIFICATION = "VERIFICATION"
    QC_PENDING = "QC_PENDING"
    QC_VERIFIED = "QC_VERIFIED"
    SUBMITTED_TO_QC = "SUBMITTED_TO_QC"
    STOP = "STOP"
    NOT_AP = "NOT_AP"
    CLEAR_VERIFIED = "CLEAR/VERIFIED"

class QCStatus(str, enum.Enum):
    PENDING_REVIEW = "PENDING_REVIEW"
    QC_IN_REVIEW = "QC_IN_REVIEW"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    ESCALATED = "ESCALATED"

class FinalResult(str, enum.Enum):
    POSITIVE = "POSITIVE"
    NEGATIVE = "NEGATIVE"
    DISCREPANCY = "DISCREPANCY"
    UNABLE_TO_VERIFY = "UNABLE_TO_VERIFY"
    INSUFFICIENT = "INSUFFICIENT"
    HOLD = "HOLD"
    AMBER = "AMBER"
    STOP = "STOP"
    NOT_AP = "NOT_AP"
    CLEAR_VERIFIED = "CLEAR/VERIFIED"

class NotificationChannel(str, enum.Enum):
    SYSTEM = "SYSTEM"
    EMAIL = "EMAIL"
    SMS = "SMS"

class NotificationCategory(str, enum.Enum):
    CASE_ASSIGNED = "CASE_ASSIGNED"
    INSUFFICIENT_DOCS = "INSUFFICIENT_DOCS"
    CASE_COMPLETED = "CASE_COMPLETED"
    FORM_SUBMITTED = "FORM_SUBMITTED"
    EMAIL_TRIGGERED = "EMAIL_TRIGGERED"
    SYSTEM_ALERT = "SYSTEM_ALERT"
    QC_REPORT_READY = "QC_REPORT_READY"
    QA_REPORT_READY = "QA_REPORT_READY"
    URGENT_PING = "URGENT_PING"

class QCIssueStatus(str, enum.Enum):
    OPEN = "OPEN"
    RESOLVED = "RESOLVED"
    CANCELLED = "CANCELLED"

class QCIssueType(str, enum.Enum):
    DATA_NOT_PROVIDED = "DATA_NOT_PROVIDED"
    DOCUMENT_UNCLEAR = "DOCUMENT_UNCLEAR"
    FIELD_MISMATCH = "FIELD_MISMATCH"
    VERIFICATION_INCOMPLETE = "VERIFICATION_INCOMPLETE"
    ADDITIONAL_PROOF_REQUIRED = "ADDITIONAL_PROOF_REQUIRED"

